# Generated by Django 4.2.25 on 2025-11-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_room_name_alter_room_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Text Message",
                "verbose_name_plural": "Text Messages",
            },
        ),
    ]
