# Generated by Django 4.2.25 on 2025-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_lng',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=3, verbose_name='Primary Language'),
        ),
    ]
