# Generated by Django 4.2.25 on 2025-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0002_customuser_primary_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="primary_lng",
            field=models.CharField(
                choices=[
                    ("eng_Latn", "English"),
                    ("arb_Arab", "Arabic"),
                    ("fra_Latn", "French"),
                ],
                default="eng_Latn",
                max_length=25,
                verbose_name="Primary Language",
            ),
        ),
    ]
