# Generated by Django 4.2.25 on 2025-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_customuser_primary_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='primary_lng',
            field=models.CharField(choices=[('eng_Latn', 'English'), ('arb_Arab', 'Arabic'), ('fra_Latn', 'French'), ('deu_Latn', 'German'), ('rus_Cyrl', 'Russian')], default='eng_Latn', max_length=25, verbose_name='Primary Language'),
        ),
    ]
