# Generated by Django 4.2.25 on 2025-12-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0004_customuser_pic_alter_customuser_primary_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_searchable",
            field=models.BooleanField(
                blank=True, default=True, help_text="enable private user", null=True
            ),
        ),
    ]
